python train.py \
	--dataset_name="cawoylel/FulaSpeechCorpora-splited-noise_augmented" \
    --tts_dataset="cawoylel/FulaNewsTextCorporaTTS" \
	--model_name_or_path="facebook/mms-300m" \
	--output_dir="./mms-300-tts" \
	--max_steps="40000" \
	--overwrite_output_dir \
	--train_split_name="train+test" \
	--eval_split_name="dev" \
	--per_device_train_batch_size="8" \
	--gradient_accumulation_steps="8" \
	--learning_rate="3e-4" \
	--warmup_steps="500" \
	--evaluation_strategy="steps" \
	--eval_steps="2000" \
	--save_strategy="steps" \
	--save_steps="1000" \
    --hub_model_id="cawoylel/windanam_mms-300m-tts" \
    --hub_strategy="every_save" \
    --preprocessing_num_workers="24" \
	--layerdrop="0.0" \
	--freeze_feature_encoder="False" \
	--gradient_checkpointing \
	--chars_to_ignore , ? . ! - \; \: \" “ % ” � \
	--fp16 \
	--group_by_length \
	--push_to_hub \
	--do_train --do_eval 